// <auto-generated />
using System;
using HospitalManagementSystem.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HospitalManagementSystem.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250719213152_addDepartmentSeed")]
    partial class addDepartmentSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HospitalManagementSystem.Core.Entities.Department", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Acil Servis"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Ağız ve Diş Sağlığı"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Aile Hekimliği"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Anesteziyoloji ve Reanimasyon"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Beyin ve Sinir Cerrahisi"
                        },
                        new
                        {
                            Id = 6L,
                            Name = "Biyokimya"
                        },
                        new
                        {
                            Id = 7L,
                            Name = "Çocuk Alerjisi"
                        },
                        new
                        {
                            Id = 8L,
                            Name = "Çocuk Cerrahisi"
                        },
                        new
                        {
                            Id = 9L,
                            Name = "Çocuk Endokrinolojisi"
                        },
                        new
                        {
                            Id = 10L,
                            Name = "Çocuk Gastroenterolojisi"
                        },
                        new
                        {
                            Id = 11L,
                            Name = "Çocuk Hematolojisi"
                        },
                        new
                        {
                            Id = 12L,
                            Name = "Çocuk Kardiyolojisi"
                        },
                        new
                        {
                            Id = 13L,
                            Name = "Çocuk Nefrolojisi"
                        },
                        new
                        {
                            Id = 14L,
                            Name = "Çocuk Nörolojisi"
                        },
                        new
                        {
                            Id = 15L,
                            Name = "Çocuk Onkolojisi"
                        },
                        new
                        {
                            Id = 16L,
                            Name = "Çocuk Psikiyatrisi"
                        },
                        new
                        {
                            Id = 17L,
                            Name = "Çocuk Sağlığı ve Hastalıkları"
                        },
                        new
                        {
                            Id = 18L,
                            Name = "Çocuk Ürolojisi"
                        },
                        new
                        {
                            Id = 19L,
                            Name = "Cildiye"
                        },
                        new
                        {
                            Id = 20L,
                            Name = "Dahiliye"
                        },
                        new
                        {
                            Id = 21L,
                            Name = "Dermatoloji"
                        },
                        new
                        {
                            Id = 22L,
                            Name = "Endokrinoloji ve Metabolizma"
                        },
                        new
                        {
                            Id = 23L,
                            Name = "Enfeksiyon Hastalıkları"
                        },
                        new
                        {
                            Id = 24L,
                            Name = "Fizik Tedavi ve Rehabilitasyon"
                        },
                        new
                        {
                            Id = 25L,
                            Name = "Gastroenteroloji"
                        },
                        new
                        {
                            Id = 26L,
                            Name = "Genel Cerrahi"
                        },
                        new
                        {
                            Id = 27L,
                            Name = "Geriatri"
                        },
                        new
                        {
                            Id = 28L,
                            Name = "Göz Hastalıkları"
                        },
                        new
                        {
                            Id = 29L,
                            Name = "Göğüs Cerrahisi"
                        },
                        new
                        {
                            Id = 30L,
                            Name = "Göğüs Hastalıkları"
                        },
                        new
                        {
                            Id = 31L,
                            Name = "Hematoloji"
                        },
                        new
                        {
                            Id = 32L,
                            Name = "İmmünoloji"
                        },
                        new
                        {
                            Id = 33L,
                            Name = "Kadın Hastalıkları ve Doğum"
                        },
                        new
                        {
                            Id = 34L,
                            Name = "Kalp ve Damar Cerrahisi"
                        },
                        new
                        {
                            Id = 35L,
                            Name = "Kardiyoloji"
                        },
                        new
                        {
                            Id = 36L,
                            Name = "Kulak Burun Boğaz"
                        },
                        new
                        {
                            Id = 37L,
                            Name = "Nefroloji"
                        },
                        new
                        {
                            Id = 38L,
                            Name = "Neonatoloji"
                        },
                        new
                        {
                            Id = 39L,
                            Name = "Nöroloji"
                        },
                        new
                        {
                            Id = 40L,
                            Name = "Nükleer Tıp"
                        },
                        new
                        {
                            Id = 41L,
                            Name = "Onkoloji"
                        },
                        new
                        {
                            Id = 42L,
                            Name = "Ortopedi ve Travmatoloji"
                        },
                        new
                        {
                            Id = 43L,
                            Name = "Patoloji"
                        },
                        new
                        {
                            Id = 44L,
                            Name = "Plastik, Rekonstrüktif ve Estetik Cerrahi"
                        },
                        new
                        {
                            Id = 45L,
                            Name = "Psikiyatri"
                        },
                        new
                        {
                            Id = 46L,
                            Name = "Psikoloji"
                        },
                        new
                        {
                            Id = 47L,
                            Name = "Radyasyon Onkolojisi"
                        },
                        new
                        {
                            Id = 48L,
                            Name = "Radyoloji"
                        },
                        new
                        {
                            Id = 49L,
                            Name = "Romatoloji"
                        },
                        new
                        {
                            Id = 50L,
                            Name = "Ruh Sağlığı ve Hastalıkları"
                        },
                        new
                        {
                            Id = 51L,
                            Name = "Spor Hekimliği"
                        },
                        new
                        {
                            Id = 52L,
                            Name = "Tıbbi Genetik"
                        },
                        new
                        {
                            Id = 53L,
                            Name = "Tıbbi Mikrobiyoloji"
                        },
                        new
                        {
                            Id = 54L,
                            Name = "Tıbbi Onkoloji"
                        },
                        new
                        {
                            Id = 55L,
                            Name = "Üroloji"
                        },
                        new
                        {
                            Id = 56L,
                            Name = "Yenidoğan Yoğun Bakım"
                        },
                        new
                        {
                            Id = 57L,
                            Name = "Yoğun Bakım"
                        });
                });

            modelBuilder.Entity("HospitalManagementSystem.Core.Entities.Doctor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("DepartmentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("HospitalManagementSystem.Core.Entities.Patient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("char(11)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TC")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("char(11)");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("HospitalManagementSystem.Core.Entities.Registration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<long>("DoctorId")
                        .HasColumnType("bigint");

                    b.Property<long>("PatientId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("HospitalManagementSystem.Core.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HospitalManagementSystem.Core.Entities.Doctor", b =>
                {
                    b.HasOne("HospitalManagementSystem.Core.Entities.Department", "Department")
                        .WithMany("Doctors")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("HospitalManagementSystem.Core.Entities.Registration", b =>
                {
                    b.HasOne("HospitalManagementSystem.Core.Entities.Doctor", "Doctor")
                        .WithMany("Registrations")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalManagementSystem.Core.Entities.Patient", "Patient")
                        .WithMany("Registrations")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HospitalManagementSystem.Core.Entities.Department", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("HospitalManagementSystem.Core.Entities.Doctor", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("HospitalManagementSystem.Core.Entities.Patient", b =>
                {
                    b.Navigation("Registrations");
                });
#pragma warning restore 612, 618
        }
    }
}
